service: auction-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  hello:
    handler: src/handlers/hello.handler
    environment:
      ACCOUNT_ID: ${aws:accountId}
    events:
      - http:
          method: GET
          path: /hello

custom:
  bundle:
    linting: false
