service: auction-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  region: eu-west-1

resources:
  Resources:
    auctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    environment:
      ACCOUNT_ID: ${aws:accountId}
    events:
      - http:
          method: POST
          path: /auction

custom:
  bundle:
    linting: false
